### ISSUE TITLE
v2 beta don't work with latest webview2

### ISSUE THREAD

**Issue by yangjuncode** [wailsapp/wails#1040]
**Description**
hello world demo doesn't run

**To Reproduce**
Steps to reproduce the behaviour:
1. install latest wails and webview2
2. wails init -n myproject
3. cd myproject, wails dev
```
INF | Serving assets from disk: R:\myproject\frontend\src
DEB | WebView2 Runtime installed: Name: 'Microsoft Edge WebView2 Runtime' Version:'96.0.1054.62' Location:'C:\Program Files (x86)\Microsoft\EdgeWebView\Application'. Minimum version required: 91.0.992.28.
panic: Failed to load shcore.dll: The specified module could not be found.

goroutine 1 [running, locked to thread]:
syscall.(*LazyProc).mustFind(0xc000093e30)
        D:/Go/src/syscall/dll_windows.go:323 +0x6c
syscall.(*LazyProc).Call(0xc000093e30, {0xc00001f9e0, 0x4, 0x4})
        D:/Go/src/syscall/dll_windows.go:339 +0x6b
github.com/leaanthony/winc/w32.GetDPIForMonitor(0x10001, 0x0, 0xc0001a4490, 0xc0001a4498)
        C:/Users/Administrator/go/pkg/mod/github.com/leaanthony/winc@v0.0.0-20211202091710-9931d43181ff/w32/shcore.go:15 +0xd9
github.com/leaanthony/winc.(*ControlBase).GetWindowDPI(0xc000186180)
        C:/Users/Administrator/go/pkg/mod/github.com/leaanthony/winc@v0.0.0-20211202091710-9931d43181ff/controlbase.go:104
+0x93
github.com/leaanthony/winc.(*ControlBase).scaleWithWindowDPI(0xc000186180, 0x2d0, 0x23a)
        C:/Users/Administrator/go/pkg/mod/github.com/leaanthony/winc@v0.0.0-20211202091710-9931d43181ff/controlbase.go:466
+0x45
github.com/leaanthony/winc.(*ControlBase).SetSize(0xc000186180, 0x2d0, 0x23a)
        C:/Users/Administrator/go/pkg/mod/github.com/leaanthony/winc@v0.0.0-20211202091710-9931d43181ff/controlbase.go:184
+0x90
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.NewWindow({0x0, 0x0}, 0xc0001060e0)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.23/internal/frontend/desktop/windows/window.go:56 +0x37d
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run(0xc0001006c0, {0xc0ba60, 0xc00017e8a0})
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.23/internal/frontend/desktop/windows/frontend.go:108 +0xd3
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run(0xc00010a700, {0xc0ba60, 0xc00017e8a0})
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.23/internal/frontend/devserver/devserver.go:139 +0xac7
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc000056320)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.23/internal/appng/app_dev.go:47 +0x52
github.com/wailsapp/wails/v2.Run(0xc0001060e0)
        C:/Users/Administrator/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.23/wails.go:24 +0xcc
main.main()
        R:/myproject/main.go:26 +0x5ff
```

**Expected behaviour**
should run ok

**System Details**
V2 users: Please add the output of `wails doctor`.
```
PS R:\myproject> wails doctor
?[0;93mWails CLI?[0m ?[0;31mv2.0.0-beta.23?[0m


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 7 Ultimate
Version:         (Build: 7601)
ID:
Go Version:     go1.17.4
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       96.0.1054.62
npm             N/A             Installed       6.14.12
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/


?[0;93m
If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
?[0m
```

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
Hi there! Looks like you're trying to use Wails on an unsupported platform. Please refer to the documentation for [supported platforms](https://wails.io/docs/gettingstarted/installation#supported-platforms).
