### ISSUE TITLE
beta.36 panics under certain circumstances

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1382]
### Discussed in https://github.com/wailsapp/wails/discussions/1376

<div type='discussions-op-text'>

<sup>Originally posted by **KiddoV** May  5, 2022</sup>
I have an app haven't run for awhile, since ``wails v2.0.0-beta.30`` I think. Now I got ``wails v2.0.0-beta.36``, and I tried ``wails dev``. The app just crash out of the batch:
```console
Wails CLI v2.0.0-beta.36


Executing: go mod tidy -compat=1.17
Executing: C:\Users\vho\go\bin\wails.exe generate module

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).AddStructToGenerateTS(0xc0000523c0, {0x1530d99, 0x4}, {0x1530d9e, 0xf}, {0x156fa80, 0xc000014f62})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:161 +0x66a
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).getMethods(0xc0000523c0, {0x15916a0, 0xc000009c00})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/reflect.go:148 +0xf29
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).Add(0xc0000523c0, {0x15916a0, 0xc000009c00})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:59 +0x35
github.com/wailsapp/wails/v2/internal/binding.NewBindings(0xc0000041e0, {0xc000044fc0, 0x1, 0x18}, {0xc000107ea8, 0x3, 0x0})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:47 +0x22b
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0x1acec0896e0)
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/appng/app_bindings.go:29 +0xa5
github.com/wailsapp/wails/v2.Run(0xc000152000)
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/wails.go:24 +0xc5
main.main()
        C:/MultiTech-Projects/GO Source Code Files/Web-Applications/Wails/xdot-controller-v2/main.go:25 +0x37b



ERROR:
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).AddStructToGenerateTS(0xc0000523c0, {0x1530d99, 0x4}, {0x1530d9e, 0xf}, {0x156fa80, 0xc000014f62})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:161 +0x66a
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).getMethods(0xc0000523c0, {0x15916a0, 0xc000009c00})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/reflect.go:148 +0xf29
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).Add(0xc0000523c0, {0x15916a0, 0xc000009c00})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:59 +0x35
github.com/wailsapp/wails/v2/internal/binding.NewBindings(0xc0000041e0, {0xc000044fc0, 0x1, 0x18}, {0xc000107ea8, 0x3, 0x0})
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/binding.go:47 +0x22b
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0x1acec0896e0)
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/appng/app_bindings.go:29 +0xa5
github.com/wailsapp/wails/v2.Run(0xc000152000)
        C:/Users/vho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/wails.go:24 +0xc5
main.main()
        C:/MultiTech-Projects/GO Source Code Files/Web-Applications/Wails/xdot-controller-v2/main.go:25 +0x37b

exit status 2

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony


exit status 1
```

Any idea what causing it?
Thanks</div>

**Comment by leaanthony** [comment]
I suspect this is to do with anonymous structs....

**Comment by leaanthony** [comment]
@kiddov - can you please try https://github.com/wailsapp/wails/pull/1383 👍 
Not only "does it run" but "are my anonymous fields still working as expected" 😄

**Comment by KiddoV** [comment]
@leaanthony looks like it works for me! Thanks a lot!!!

**Comment by leaanthony** [comment]
Merged 👍
