### ISSUE TITLE
segfault for wails dev/build on v2.0.0-beta.39.2

### ISSUE THREAD

**Issue by cookiengineer** [wailsapp/wails#1608]
### Description

As the title says, `wails dev` leads to a segfault with `go version go1.18.3 linux/amd64` on Arch Linux:

```bash
💻 wails dev
Wails CLI v2.0.0-beta.39.2


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d8318]

goroutine 1 [running]:
github.com/Masterminds/semver.(*Version).Compare(0x9dab3a?, 0x10?)
	/home/cookiengineer/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:268 +0x18
github.com/Masterminds/semver.(*Version).Equal(...)
	/home/cookiengineer/go/pkg/mod/github.com/!masterminds/semver@v1.5.0/version.go:257
github.com/wailsapp/wails/v2/internal/gomod.GoModOutOfSync({0xc0001ca200?, 0xc00019ad80?, 0x0?}, {0x9dab3a, 0x10})
	/home/cookiengineer/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.39.2/internal/gomod/gomod.go:42 +0xb6
github.com/wailsapp/wails/v2/cmd/wails/internal/commands/dev.syncGoModVersion({0xc00002c004?, 0x16?})
	/home/cookiengineer/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.39.2/cmd/wails/internal/commands/dev/dev.go:286 +0xab
github.com/wailsapp/wails/v2/cmd/wails/internal/commands/dev.AddSubcommand.func1()
	/home/cookiengineer/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.39.2/cmd/wails/internal/commands/dev/dev.go:154 +0x1c6
github.com/leaanthony/clir.(*Command).run(0x942540?, {0xc000020050?, 0x7ffced267a61?, 0x3?})
	/home/cookiengineer/go/pkg/mod/github.com/leaanthony/clir@v1.0.4/command.go:97 +0x15b
github.com/leaanthony/clir.(*Command).run(0xc00019a3f0, {0xc000020050?, 0x1, 0x1})
	/home/cookiengineer/go/pkg/mod/github.com/leaanthony/clir@v1.0.4/command.go:77 +0x228
github.com/leaanthony/clir.(*Cli).Run(0xc0001ac990?, {0x0?, 0x7?, 0x9dd9b7?})
	/home/cookiengineer/go/pkg/mod/github.com/leaanthony/clir@v1.0.4/cli.go:72 +0xa5
main.main()
	/home/cookiengineer/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.39.2/cmd/wails/main.go:76 +0x339
```

### To Reproduce

When executing the following commands, it leads to a segfault:

```bash
wails init -t plain -n whatever;

cd whatever;

wails dev; # segfaults
```

### Expected behaviour

No segfault?

The segfault also happens with the identical callstack for `wails build`.

### System Details

```shell
💻 wails doctor
Wails CLI v2.0.0-beta.39.2

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Arch Linux
Version: 	Unknown
ID:		arch
Go Version:	go1.18.3
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.39.2
Package Manager: 	pacman

Dependency	Package Name	Status		Version
----------	------------	------		-------
*docker		docker		Installed	1:20.10.17-1
gcc		gcc		Installed	12.1.0-2
libgtk-3	gtk3		Installed	1:3.24.34-1
libwebkit	webkit2gtk	Installed	2.36.3-1
npm		npm		Installed	8.5.5-1
pkg-config	pkgconf		Installed	1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by leaanthony** [comment]
Just be aware there are breaking changes between v1 and v2 so running `wails dev` on a v1 app won't work 👍
