### ISSUE TITLE
Crash during typescript generation if struct contains anonymous sub-struct

### ISSUE THREAD

**Issue by avengerweb** [wailsapp/wails#2038]
### Description

Crash during typescript generation if struct contains anonymous sub-struct

```
Build error - 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).AddStructToGenerateTS(0x14000210000, {0x1400021e198, 0x8}, {0x10103cdbc, 0x4}, {0x1010a8260?, 0x1400020e0c0})
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/binding/binding.go:202 +0x558
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).getMethods(0x14000210000, {0x1010c80a0?, 0x1400000f3c8})
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/binding/reflect.go:138 +0xc4c
github.com/wailsapp/wails/v2/internal/binding.(*Bindings).Add(0x14000210000, {0x1010c80a0?, 0x1400000f3c8?})
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/binding/binding.go:62 +0x2c
github.com/wailsapp/wails/v2/internal/binding.NewBindings(0x1400000f3f8, {0x14000021550, 0x1, 0x100effee0?}, {0x14000111e58, 0x4, 0x1400011e480?}, 0x0)
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/binding/binding.go:50 +0x1ec
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0x14000021560?)
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/app/app_bindings.go:28 +0xa4
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0x1400000f3e0)
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/pkg/application/application.go:69 +0x168
github.com/wailsapp/wails/v2.Run(0x140000010e0?)
        /Users/avengerweb/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/wails.go:14 +0xb0

```

### To Reproduce

Any method that returns struct with anonymous struct will produce error on compilation stage:

```golang
type Demo struct {
	Data []struct {
		Name string `json:"name"`
	} `json:"data"`
}

func (a *App) GetDemo() *internal.Demo {
	news := &internal.Demo{}

	return news
}
```

### Expected behaviour

- Anonymous struct should be built as "unknown/any" type
- Or clear message should be displayed (like we don't support anonymous sub-struct)

### System Details

```shell
% wails doctor
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        13.0
ID:             22A5342f
Go Version:     go1.18.4
Platform:       darwin
Architecture:   arm64

Wails
------
Version:        v2.1.0

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2396
npm                             N/A             Installed       8.15.0
*upx                            N/A             Available       
*nsis                           N/A             Available       

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```
```


### Additional context

_No response_

**Comment by leaanthony** [comment]
@avengerweb - thanks for reporting this. Any chance you could create a PR with a test that shows this? TS tests can be found [here](https://github.com/wailsapp/wails/tree/master/v2/internal/binding/binding_test). Remember to add your test to the `binding_test.go` file.
We should be able to build a fix then. Thanks 👍

**Comment by stffabi** [comment]
The PR has been merged and will be part of the next release.
