### ISSUE TITLE
Support Distribution 'KDE neon'

### ISSUE THREAD

**Issue by Bleser** [wailsapp/wails#230]
**Description**
Distribution 'neon' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.14-pre |
| Go Version    | go1.12.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | neon |
| Distribution Name   | KDE neon |
| Distribution Version   | 18.04 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
hello @Bleser the PR is ready, you can either wait for @leaanthony to merge and tag so you can use `wails update -pre`
or if you'd like to also help checking before the merge fetch it from my repo instead like this
`git clone -b 230-support-distribution-kde-neon https://github.com/bh90210/wails.git && cd wails/cmd/wails && go install && wails setup`

**Comment by Bleser** [comment]
@bh90210 everything works, but when building Vue2 / Webpack Basic I get an error:

``` 
$ wails build
Wails v0.17.14-pre - Building Application (force rebuild)

✓ Ensuring frontend dependencies are up to date (This may take a while)
⡿ Building frontend...-  Building for production...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at fileFilter (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:71:30)
    at Array.filter (<anonymous>)
    at compiler.hooks.afterEmit.tap.compilation (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:82:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/webpack/lib/Compiler.js:482:27)
    at /home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/neo-async/async.js:2818:7
    at done (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/webpack/lib/Compiler.js:464:33)
    at /home/bleser/PROJECTS/GO/test_wails/frontend/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test_wails@ build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test_wails@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bleser/.npm/_logs/2019-09-13T07_37_04_318Z-debug.log


> test_wails@ build /home/bleser/PROJECTS/GO/test_wails/frontend
> vue-cli-service build



✗ Building frontend...
Error: exit status 1```

**Comment by bh90210** [comment]
uh I'm afraid I can't reproduce
```
wails init
Wails v0.17.14-pre - Initialising project

The name of the project (My Project): 
Project Name: My Project
The output binary name (my-project): 
Output binary Name: my-project
Project directory name (my-project): 
Project Directory: my-project
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
✓ Generating project...
✓ Building project (this may take a while)...
Project 'My Project' built in directory 'my-project'!
```

**Comment by bh90210** [comment]
ok I just noticed,
please try again without the `-f` flag

**Comment by Bleser** [comment]
@bh90210 

Step №1 (Success):
```
➜ bleser ~/PROJECTS/GO /home/bleser/PROJECTS/GO/for_test/wails/cmd/wails/wails init                                                                                                  12:59:33
Wails v0.17.14-pre - Initialising project

The name of the project (My Project): 
Project Name: My Project
The output binary name (my-project): 
Output binary Name: my-project
Project directory name (my-project): 
Project Directory: my-project
Please select a template:
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v3 template
  3: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  4: Vuetify Basic - Vuetify + Webpack
Please choose an option [1]: 3
Template: Vue2/Webpack Basic
✓ Generating project...
✓ Building project (this may take a while)...
Project 'My Project' built in directory 'my-project'!
```

Step №2 (Failed):
```
➜ bleser ~/PROJECTS/GO cd my-project                                                                                                                                                 13:00:36
➜ bleser ~/PROJECTS/GO/my-project /home/bleser/PROJECTS/GO/for_test/wails/cmd/wails/wails build                                                                                      13:01:25
Wails v0.17.14-pre - Building Application

✓ Skipped frontend dependencies (-f to force rebuild)
⢿ Building frontend...-  Building for production...
 ERROR  TypeError: Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at fileFilter (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:71:30)
    at Array.filter (<anonymous>)
    at compiler.hooks.afterEmit.tap.compilation (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:82:31)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/webpack/lib/Compiler.js:482:27)
    at /home/bleser/PROJECTS/GO/my-project/frontend/node_modules/neo-async/async.js:2818:7
    at done (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (/home/bleser/PROJECTS/GO/my-project/frontend/node_modules/webpack/lib/Compiler.js:464:33)
    at /home/bleser/PROJECTS/GO/my-project/frontend/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my_project@ build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my_project@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bleser/.npm/_logs/2019-09-13T08_01_34_112Z-debug.log


> my_project@ build /home/bleser/PROJECTS/GO/my-project/frontend
> vue-cli-service build



✗ Building frontend...
Error: exit status 1
```

Command `go run main.go` open black screen

![Screenshot_20190913_130708](https://user-images.githubusercontent.com/12870298/64847025-76665f80-d627-11e9-9627-35c07f892433.png)

**Comment by leaanthony** [comment]
Can you confirm that your ~/wails/wails.json is present and valid json? thanks.

**Comment by Bleser** [comment]
@leaanthony 
```json
{"email":"email@gmail.com","name":"Bleser"}
```

**Comment by Bleser** [comment]
I found a [workaround](https://stackoverflow.com/questions/57916549/vue-cli-run-build-typeerror-name-undefined)

```
module.exports = {
  productionSourceMap: false
}
```

**Comment by leaanthony** [comment]
@Bleser - Neon support added. Update wails to v0.17.15-pre using `wails update -pre`. If you have time, please do a PR for the sourcemap fix as I'd like to look at it to see if it affects the other systems.

**Comment by bh90210** [comment]
also just for future reference I also encountered the `TypeError: Cannot read property 'name' of undefined` problem and the solution was to run `npm install` :+1:

**Comment by Bleser** [comment]
I want to know if there will be [pnpm](https://pnpm.js.org) support in the future?

**Comment by bh90210** [comment]
hey @Bleser 
I doubt it. at least not for now...

**Comment by leaanthony** [comment]
I like pnpm. Let's look post v1.
