### ISSUE TITLE
Failed to unregister class Chrome_WidgetWin_0. Error

### ISSUE THREAD

**Issue by geekroscom** [wailsapp/wails#2301]
### Description

Go：

```
func (a *Api) Startup(ctx context.Context) {
...
}
func (a *Api) Shutdown(ctx context.Context) {
...
}
func (a *Api) Download(uri string, callback func(status bool, length int64, downLen int64)) {
...
}
```
ERROR:

```
goroutine 121 [running]:
geekstudio/framework/windows/start.(*Api).Download(0xc00007a7e0, {0x0, 0x0}, 0x0)
        D:/Geek_Studio/framework/windows/start/index.go:50 +0x120
reflect.Value.call({0x199e720, 0xc00007a7e0, 0x213}, {0x1a3e4cc, 0x4}, {0xc000108480, 0x2, 0x2})
        F:/ProgramFiles/GoLang/src/reflect/value.go:584 +0xc76
reflect.Value.Call({0x199e720, 0xc00007a7e0, 0x213}, {0xc000108480, 0x2, 0x2})
        F:/ProgramFiles/GoLang/src/reflect/value.go:368 +0xb7
github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call(0xc00046bf80, {0xc000444220, 0x2, 0x2})
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/binding/boundMethod.go:73 +0x33b
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage(0xc00007e840, {0xc000093490, 0x69}, {0x1ca1050, 0xc00012a280})
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/frontend/dispatcher/calls.go:45 +0x5a9
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage(0xc00007e840, {0xc000093490, 0x69}, {0x1ca1050, 0xc00012a280})
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/frontend/dispatcher/dispatcher.go:40 +0x245
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage.func1()
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/frontend/desktop/windows/frontend.go:596 +0x91
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage
        C:/Users/admin/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/frontend/desktop/windows/frontend.go:595 +0x678
[0115/174456.129:ERROR:window_impl.cc(119)] Failed to unregister class Chrome_WidgetWin_0. Error = 0

```

### To Reproduce

ADD：
```
func (a *Api) Download(uri string, callback func(status bool, length int64, downLen int64)) {
...
}
```

VUE：

```
(window as any).go.StartWindows.Api.Download("", (err: any, length: any, download: any)=>{
console.log(err, length, download);
});
```

### Expected behaviour

VUE：

```
(window as any).go.StartWindows.Api.Download("", (err: any, length: any, download: any)=>{
console.log(err, length, download);
});
```

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro     
# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 109.0.1518.52
npm        | N/A          | Installed | 8.5.0
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

```
```


### Additional context

_No response_

**Comment by robomentor** [comment]
It's done!
