### ISSUE TITLE
[v2][macOS][Catalina] fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by zllovesuki** [wailsapp/wails#2394]
### Description

Running `wails dev` shows the frontend for a split second, then the terminal has panic message:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7fff4132f577]

runtime stack:
runtime.throw({0x100caa8d6?, 0x12d201a00?})
        /opt/local/lib/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffeefbfdbe0 sp=0x7ffeefbfdbb0 pc=0x100042e1d
runtime.sigpanic()
        /opt/local/lib/go/src/runtime/signal_unix.go:821 +0x285 fp=0x7ffeefbfdc10 sp=0x7ffeefbfdbe0 pc=0x10005a9a5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x100af6c60, 0xc00022fd30)
        /opt/local/lib/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00022fd08 sp=0xc00022fcd0 pc=0x100009efc
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin._Cfunc_RunMainLoop()
        _cgo_gotypes.go:617 +0x45 fp=0xc00022fd30 sp=0xc00022fd08 pc=0x100a78045
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).RunMainLoop(0xc0002ed6e0)
        /Users/rachel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/frontend/desktop/darwin/frontend.go:59 +0x1c fp=0xc00022fd40 sp=0xc00022fd30 pc=0x100a7c29c
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).RunMainLoop(0xc0001feea0)
        <autogenerated>:1 +0x34 fp=0xc00022fd58 sp=0xc00022fd40 pc=0x100ae8af4
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc0001af7c0)
        /Users/rachel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/internal/app/app_dev.go:30 +0x72 fp=0xc00022fdc0 sp=0xc00022fd58 pc=0x100af2052
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc0001c1f80)
        /Users/rachel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/pkg/application/application.go:80 +0x28f fp=0xc00022fe90 sp=0xc00022fdc0 pc=0x100af5a8f
github.com/wailsapp/wails/v2.Run(0xc0001d7cc0)
        /Users/rachel/go/pkg/mod/github.com/wailsapp/wails/v2@v2.3.1/wails.go:14 +0x33 fp=0xc00022fed0 sp=0xc00022fe90 pc=0x100af60f3
main.main()
        /Users/rachel/code/phantom/main.go:22 +0x425 fp=0xc00022ff80 sp=0xc00022fed0 pc=0x100af6565
runtime.main()
        /opt/local/lib/go/src/runtime/proc.go:250 +0x1d3 fp=0xc00022ffe0 sp=0xc00022ff80 pc=0x100045553
runtime.goexit()
        /opt/local/lib/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00022ffe8 sp=0xc00022ffe0 pc=0x10007a8e1
```

### To Reproduce

Clone https://github.com/zllovesuki/phantom and run `wails dev`

### Expected behaviour

Frontend shows up correctly and no panic

### System Details

```shell
❯ wails doctor
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 10.15.7
ID           | 19H2026
Go Version   | go1.20.1
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2373
npm                       | N/A          | Installed | 9.3.1
*Xcode                    | N/A          | Installed | 12.2 (12B45b)
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```
```


### Additional context

the result app bundle from `wails build` works correctly though

**Comment by leaanthony** [comment]
Thanks for opening this. 10.15 is pretty old but it should work. Is this reproducible with the standard template? Likely there's an API being used that isn't supported.

**Comment by zllovesuki** [comment]
@leaanthony I just tried it on a standard template with `vue-ts`, that one works with no problem. Interesting

**Comment by leaanthony** [comment]
Sounds like you may need to debug a bit more. Try wrapping the main calls with a recover statement for more info

**Comment by leaanthony** [comment]
Fantastic debugging! I'm sure there's an API guard for that but we'll check if it's correct. Also, don't use that if you want to submit your app to the app store as it's likely to not pass the checks (private API)

**Comment by stffabi** [comment]
Nice catch, seems like the guard is really missing there.

> Also, don't use that if you want to submit your app to the app store as it's likely to not pass the checks (private API)

As long as a production build is used, the flag should not be a problem, because all the private API code is not included in a production build.

**Comment by stffabi** [comment]
I've opened PR #2397 to fix this issue. It will just ignore opening the inspector on older macOS versions and log it to the console.
