### ISSUE TITLE
Unable to trigger successfully bound method

### ISSUE THREAD

**Issue by netrounds-martin** [wailsapp/wails#240]
**Description**

When attempting to trigger a bound method using a frontend button, nothing happens. I am however able to trigger it when attempting to do so with a regular function.

I am unable to get the below code to run upon pressing the button. However, when I remove the "a *App" part, and adjust the tx function() by removing the .App part. It runs fine. 

App.vue
```vuejs

<p-button type="info" block @click.native="tx"></p-button>

export default {
    methods: {
        tx: function() {
            window.backend.App.PrepareTransaction()
        }
    }
}
```

main.go
```golang
func (a *App) PrepareTransaction() {
fmt.Println("hello world")
}
```

Wails report:
`INFO[0000] [Bind] Bound Method: main.App.PrepareTransaction()`

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to trigger a Go method from VueJS
2. Try to manually trigger a Go function from VueJS

**Expected behaviour**
I expect the button press to trigger "Hello world" in both cases. 

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.15-pre |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 7.4.0 |
| Npm           | v12.10.0 |
| Node          | 6.10.3 |

**Additional context**

**Comment by netrounds-martin** [comment]
`3C%2Fbody%3E%0A%3C%2Fhtml%3E:26:131916: CONSOLE ERROR Unhandled Promise Rejection: TypeError: window.backend.App.prepareTransaction is not a function. (In 'window.backend.App.prepareTransaction(n,r)', 'window.backend.App.prepareTransaction' is undefined)`

**Comment by netrounds-martin** [comment]
`CONSOLE ERROR Unhandled Promise Rejection: TypeError: window.backend.App.PrepareTransaction is not a function. (In 'window.backend.App.PrepareTransaction(n,r)', 'window.backend.App.PrepareTransaction' is undefined)` is reported when the app is compiled.

**Comment by leaanthony** [comment]
Hi. You may have bound your struct incorrectly. I knocked up a quick example that mimics your desired behaviour:

`main.go`
```go
package main

import (
	"github.com/leaanthony/mewn"
	"github.com/wailsapp/wails"
)

func main() {

	js := mewn.String("./frontend/dist/app.js")
	css := mewn.String("./frontend/dist/app.css")

	app := wails.CreateApp(&wails.AppConfig{
		Width:  1024,
		Height: 768,
		Title:  "structtest",
		JS:     js,
		CSS:    css,
		Colour: "#131313",
	})
	app.Bind(&App{})   // Your bound struct needs to be a created instance
	app.Run()
}
```

`app.go`:
```go
package main

import "fmt"

type App struct{}

func (a *App) PrepareTransaction() {
	fmt.Println("hello world")
}
```

`helloworld.vue`
```javascript
 ...
 ...
  methods: {
    getMessage: function() {
      var self = this;
      window.backend.App.PrepareTransaction().then(result => {
        self.message = result;
      });
    }
  }
  ...
  ...
```

Result after pressing button:
```bash
leas-MacBook-Pro:structtest lea$ ./structtest 
structtest - Debug Build
------------------------
INFO[0000] [App] Starting                               
INFO[0000] [WebView] Initialised                        
INFO[0000] [Events] Starting                            
INFO[0000] [Events] Listening                           
INFO[0000] [IPC] Starting                               
INFO[0000] [Bind] Starting                              
INFO[0000] [Bind] Binding Go Functions/Methods          
INFO[0000] [Bind] Bound Method: main.App.PrepareTransaction() 
INFO[0000] [WebView] Run()                              
INFO[0000] [WebView] 1                                  
INFO[0000] [WebView] 2                                  
hello world
```

Hope that helps 👍

**Comment by netrounds-martin** [comment]
This is literally how I've got it set up. Very odd. When I try to trigger it this is what the Console is displaying.

```
Uncaught (in promise) TypeError: window.backend.App.PrepareTransaction is not a function
    at eval (Transactions.vue?539c:77)
```

However if I use it as a function instead and bind it individually - it works fine.

**Comment by netrounds-martin** [comment]
I tried binding to method to a clear type struct, then it worked fine. So I've narrowed down the problem to binding this struct to my method.

```golang 
type WalletApplication struct {
	RT    *wails.Runtime
	log   *wails.CustomLogger
	paths struct {
		HomeDir    string
		DAGDir     string
		KeyFile    string
		LastTXFile string
	}
	wallet *Wallet
}
```

**Comment by leaanthony** [comment]
I tried again for you, using the following app.go:

```
package main

import (
	"fmt"

	"github.com/wailsapp/wails"
)

type App struct {
	RT    *wails.Runtime
	log   *wails.CustomLogger
	paths struct {
		HomeDir    string
		DAGDir     string
		KeyFile    string
		LastTXFile string
	}
	// wallet *Wallet
}

func (a *App) PrepareTransaction() {
	fmt.Println("hello world")
}
```

It worked fine! Maybe it can't resolve `wallet` and the build is failing silently?

**Comment by netrounds-martin** [comment]
Thank you for this. I really appreciate you spending time on assisting me with this. 

When I remove the Wallet struct from App, it works for me too. The odd thing is that I'm Emiting the objects inside the wallet struct to the frontend. With no problems what so ever.

**Comment by leaanthony** [comment]
Hmmm.. Are you passing the Runtime object into the Wallet to be able to Emit? Are you able to share more of your code so I can test further?

**Comment by netrounds-martin** [comment]
Nope, this is an example of how I'm utilizing the Runtime across my code base.

```golang 
func (a *WalletApplication) passKeysToFrontend() {
	go func() {
		for {
			a.RT.Events.Emit("wallet_keys", a.Wallet.PrivateKey.Key, a.Wallet.PublicKey.Key)
			time.Sleep(5 * time.Second)
		}
	}()
```

This is the Wallet struct.
```golang
// Wallet holds all wallet information.
type Wallet struct {
	Balance          int    `json:"balance"`
	AvailableBalance int    `json:"available_balance"`
	Nonce            int    `json:"nonce"`
	TotalBalance     int    `json:"total_balance"`
	Delegated        int    `json:"delegated"`
	Deposit          int    `json:"deposit"`
	Address          []byte `json:"address"`
	TokenPrice       struct {
		DAG struct {
			BTC float64 `json:"BTC,omitempty"`
			USD float64 `json:"USD,omitempty"`
			EUR float64 `json:"EUR,omitempty"`
		} `json:"DAG"`
	} `json:"token_price"`
	PrivateKey struct {
		Key string `json:"key"`
	} `json:"privateKey"`
	PublicKey struct {
		Key string `json:"key"`
	} `json:"publicKey"`
}
```
I'll send an invite to the repo.

**Comment by grvlle** [comment]
I actually managed to resolve it. By not calling this function.

```golang
func (a *WalletApplication) pricePoller() {

	const (
		apiKey string = "******"
		ticker string = "***"
		url    string = "https://min-api.cryptocompare.com/data/pricemulti?fsyms=" + ticker + "&tsyms=BTC,USD,EUR&api_key=" + apiKey
	)

	go func() {
		for {
			resp, err := http.Get(url)
			if err != nil {
				a.log.Warnf("Unable to poll token evaluation", err) // Log this
			}
			defer resp.Body.Close()
			body, err := ioutil.ReadAll(resp.Body)
			if err != nil {
				a.log.Warnf("Unable to read HTTP resonse from Token API. Reason: ", err)
			}
			err = json.Unmarshal([]byte(body), &a.Wallet.TokenPrice)
			if err != nil {
				a.log.Warnf("Unable to display token price. Reason:", err)
			}

			a.RT.Events.Emit("price", "$", a.Wallet.TokenPrice.DAG.USD)
			time.Sleep(updateIntervalToken * time.Second)
		}
	}()
}
```

**Comment by netrounds-martin** [comment]
I managed to resolve it by commenting out a go routine interacting with the Wallet. 

```golang
func (a *WalletApplication) pricePoller() {

	const (
		apiKey string = ""
		ticker string = ""
		url    string = "https://min-api.cryptocompare.com/data/pricemulti?fsyms=" + ticker + "&tsyms=BTC,USD,EUR&api_key=" + apiKey
	)

	go func() {
		for {
			resp, err := http.Get(url)
			if err != nil {
				a.log.Warnf("Unable to poll token evaluation", err) // Log this
			}
			defer resp.Body.Close()
			body, err := ioutil.ReadAll(resp.Body)
			if err != nil {
				a.log.Warnf("Unable to read HTTP resonse from Token API. Reason: ", err)
			}
			err = json.Unmarshal([]byte(body), &a.Wallet.TokenPrice)
			if err != nil {
				a.log.Warnf("Unable to display token price. Reason:", err)
			}

			a.RT.Events.Emit("price", "$", a.Wallet.TokenPrice.DAG.USD)
			time.Sleep(updateIntervalToken * time.Second)
		}
	}()
}
```

**Comment by leaanthony** [comment]
Glad you got it sorted. Am interested to know why this would affect it.

**Comment by netrounds-martin** [comment]
This is super odd. I re-introduced the pricePoller() func and I can still call the method. BUT, when doing so - I am now triggering a panic:

```golang
{}
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 79 [running]:
github.com/wailsapp/wails/lib/binding.(*Manager).ProcessCall.func1(0xc00062fce0)
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/binding/manager.go:254 +0x15c
panic(0x833a20, 0x113efc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
main.(*WalletApplication).updateLastTransactions(0xc0000ac420)
	/home/vito/Documents/code/go/constellation_wallet/transactions.go:131 +0x7e8
main.(*WalletApplication).sendTransaction(0xc0000ac420, 0x3eeddc, 0xa, 0xc00024a6e0, 0x6)
	/home/vito/Documents/code/go/constellation_wallet/transactions.go:99 +0x57b
main.(*WalletApplication).PrepareTransaction(0xc0000ac420, 0x3eeddc, 0xc00024a6e0, 0x6, 0x0)
	/home/vito/Documents/code/go/constellation_wallet/transactions.go:69 +0x8d
reflect.Value.call(0x88b7a0, 0xc0000ac420, 0x613, 0x8aa300, 0x4, 0xc0001e99e0, 0x2, 0x2, 0x2, 0xc0010181c0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x461
reflect.Value.Call(0x88b7a0, 0xc0000ac420, 0x613, 0xc0001e99e0, 0x2, 0x2, 0x1, 0xc000223520, 0x98)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/wailsapp/wails/lib/binding.(*boundMethod).call(0xc00010e080, 0xc0002332a0, 0x12, 0x29, 0xc00010c160, 0xc00005abb0, 0x449027, 0xc00005ac57)
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/binding/method.go:143 +0x6aa
github.com/wailsapp/wails/lib/binding.(*Manager).processMethodCall(0xc000614180, 0xc0002279a0, 0xc00005ace0, 0x19, 0xc00005aca0, 0x1)
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/binding/manager.go:212 +0xa7
github.com/wailsapp/wails/lib/binding.(*Manager).ProcessCall(0xc000614180, 0xc0002279a0, 0x0, 0x0, 0x0, 0x0)
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/binding/manager.go:262 +0x378
github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1.1(0xc6e800, 0xc000614180, 0xc0002279a0, 0xc0000ae0c0, 0xc0001f2020)
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/ipc/manager.go:64 +0x59
created by github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1
	/home/vito/Documents/code/go/pkg/mod/github.com/wailsapp/wails@v0.17.13-pre/lib/ipc/manager.go:63 +0xada
Error: exit status 2

```
