### ISSUE TITLE
The program created using "wails init -n" cannot be launched. It throws an error when running "wails dev" without making any modifications.

### ISSUE THREAD

**Issue by netskyline** [wailsapp/wails#2756]
### Description

The program created using "wails init -n" cannot be launched. It throws an error when running "wails dev" without making any modifications.

### To Reproduce

1. wails init -n myproject1 -t react
2. cd myproject1
3. wails dev

### Expected behaviour

An error hath occurred whilst executing the command "wails dev.":

$ wails dev
Wails CLI v2.5.1

Executing: go mod tidy
  • Generating bindings:
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:

    > frontend@0.0.0 build
    > vite build

    error during build:
    SyntaxError: Invalid regular expression: /(?<![\p{L}\p{N}_$]|(?<!\.\.)\.)(process\.env\.NODE_ENV|global\.process\.env\.NODE_ENV|globalThis\.process\.env\.NODE_ENV|__vite_process_env_NODE_ENV|import\.meta\.env\.BASE_URL|import\.meta\.env\.MODE|import\.meta\.env\.DEV|import\.meta\.env\.PROD|import\.meta\.env\.SSR|import\.meta\.env\.|import\.meta\.env|import\.meta\.hot|process\.env\.|global\.process\.env\.|globalThis\.process\.env\.)(?:(?<=\.)|(?![\p{L}\p{N}_$]|\s*?=[^=]))/: Invalid property name in character class
        at new RegExp (<anonymous>)
        at generatePattern (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:37938:15)
        at definePlugin (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:37953:28)
        at resolvePlugins (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40032:9)
        at async resolveConfig (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62867:24)
        at async doBuild (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45631:20)
        at async build (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45620:16)
        at async CAC.<anonymous> (file:///Users/genodong/projects/test-wails/myproject1/frontend/node_modules/vite/dist/node/cli.js:756:9)

  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

### System Details

```shell
$ wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | MacOS
Version      | 13.4.1
ID           | 22F82
Go Version   | go1.19.5
Platform     | darwin
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397
Nodejs                    | N/A          | Installed | 18.16.0
npm                       | N/A          | Installed | 9.5.1
*Xcode                    | N/A          | Available |
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Unable to reproduce this I'm afraid!

**Comment by netskyline** [comment]
The problem was resolved after upgrading Node.js to version v18.16.1.
