### ISSUE TITLE
MacOS: Crash when using runtime.EventsEmit within exported callback for C

### ISSUE THREAD

**Issue by APshenkin** [wailsapp/wails#2902]
### Description

Hi

First thank you for this project!

I'm trying to implement support for CustomURL scheme with wails. It works well and I was able to get url within the app.
However I want to return this url to frontend using `runtime.EventsEmit`, but face application crash when it's called within exported C function. Maybe I cook this in wrong way 🤔

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1af30e02d30 pc=0x19d01c5f8]

runtime stack:
runtime.throw({0x10480ab1e?, 0x0?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:1047 +0x40 fp=0x16bbbcab0 sp=0x16bbbca80 pc=0x1042796f0
runtime.sigpanic()
	/opt/homebrew/opt/go/libexec/src/runtime/signal_unix.go:821 +0x20c fp=0x16bbbcae0 sp=0x16bbbcab0 pc=0x10428ed7c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1047e1da4, 0x140001f5d68)
	/opt/homebrew/opt/go/libexec/src/runtime/cgocall.go:157 +0x50 fp=0x140001f5d30 sp=0x140001f5cf0 pc=0x1042477b0
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin._Cfunc_RunMainLoop()
	_cgo_gotypes.go:538 +0x30 fp=0x140001f5d60 sp=0x140001f5d30 pc=0x104729d30
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).RunMainLoop(0x140001c6a20)
	/Users/andrey.pshenkin/git/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/frontend/desktop/darwin/frontend.go:63 +0x20 fp=0x140001f5d70 sp=0x140001f5d60 pc=0x10472d190
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).RunMainLoop(0x1400014ce10)
	<autogenerated>:1 +0x3c fp=0x140001f5d90 sp=0x140001f5d70 pc=0x1047d40fc
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0x1400013e820)
	/Users/andrey.pshenkin/git/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/internal/app/app_dev.go:33 +0x78 fp=0x140001f5e00 sp=0x140001f5d90 pc=0x1047dc8d8
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0x1400013cfa0)
	/Users/andrey.pshenkin/git/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/pkg/application/application.go:72 +0x16c fp=0x140001f5ea0 sp=0x140001f5e00 pc=0x1047df77c
github.com/wailsapp/wails/v2.Run(0x14000164500)
	/Users/andrey.pshenkin/git/go/pkg/mod/github.com/wailsapp/wails/v2@v2.6.0/wails.go:14 +0x30 fp=0x140001f5ee0 sp=0x140001f5ea0 pc=0x1047df970
main.main()
	/Users/andrey.pshenkin/git/wails-HandleURL-crash/main.go:29 +0x320 fp=0x140001f5f70 sp=0x140001f5ee0 pc=0x1047e0180
runtime.main()
	/opt/homebrew/opt/go/libexec/src/runtime/proc.go:250 +0x1d4 fp=0x140001f5fd0 sp=0x140001f5f70 pc=0x10427ba54
runtime.goexit()
	/opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001f5fd0 sp=0x140001f5fd0 pc=0x1042a97e4
```

### To Reproduce

here is the repo with template project and required changes

https://github.com/APshenkin/wails-HandleURL-crash

```
wails dev

then in other terminal
open myapp://hello/world
```

### Expected behaviour

Callback should be raised without issues

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 13.5.1   |
| ID           | 22G90    |
| Go Version   | go1.20.2 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version          |
| Xcode command line tools  | N/A          | Installed | 2397             |
| Nodejs                    | N/A          | Installed | 16.15.0          |
| npm                       | N/A          | Installed | 8.19.3           |
| *Xcode                    | N/A          | Installed | 14.3.1 (14E300c) |
| *upx                      | N/A          | Available |                  |
| *nsis                     | N/A          | Available |                  |
└──────────────────────── * - Optional Dependency ────────────────────────┘
```

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

I only took a brief look into your code and maybe it is related to a timing issue.
Maybe the wailsContext is nil at the time the native callback is getting called. You might need to defer the emit until the context is there and your frontend is really loaded and is able to handle the event.

**Comment by stffabi** [comment]
I think I know what's going on, the callback is called with an autorelease pool, whereas most of the Wails code assumes there's no autorelease pool. So there are cases where memory is released multiple times.

Can you try to spawn a new goroutine for emitting the event `go runtime.EventsEmit(*wailsContext, "foo", test)`? That might be the easiest for you to get it solved.

**Comment by APshenkin** [comment]
@stffabi you are right, thank you for your help :)
