### ISSUE TITLE
Is there any convenient way to package the frontend for browser access?

### ISSUE THREAD

**Issue by geekroscom** [wailsapp/wails#3075]
### Is your feature request related to a problem? Please describe.

I hope that the packaged frontend resources can be used directly in the browser. Currently, accessing it with the browser results in an error.

### Describe the solution you'd like

null

### Describe alternatives you've considered

Redevelop?

### Additional context

```
start.vue:69 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'EventsOn')
    at setup (start.vue:69:33)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5773:9)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5814:51)
```

**Comment by geekros** [comment]
Or is there any way to access http://wails.localhost/ in the browser?

**Comment by dtapps** [comment]
me too

**Comment by RuntimeRacer** [comment]
BUMP!

@geekroscom did you ever find a solution for this?

Right now I am working on an application that is actually meant to be run standalone on a client's PC, however I'd also like to provide an option to run it inside of a docker container or Kubernetes pod for simpler quickstart, but being able to access the UI via browser to configure it conveniently.

**Comment by RuntimeRacer** [comment]
Since that issue seems to have gotten some traction: I went ahead and solved this by just adding a REST API to my application and making the UI standalone capable; you can take a look here if anyone needs inspiration to go that route: https://github.com/harmony-ai-solutions/harmony-link-ui

**Comment by leaanthony** [comment]
Yes — this is addressed by the v3 **server build**.

Building with `go build -tags server` (or `wails3 task build:server`) starts an HTTP server that serves your frontend over plain HTTP *and* serves a working Wails JS runtime: method calls (`wails.Call...`) are bridged over HTTP, and events (`wails.Events.On`/`Emit`) over a WebSocket. So `EventsOn`/`Call` are no longer `undefined` when the app is opened in a normal browser tab — which was the error in the original report.

- Example: `examples/server` (includes a Dockerfile)
- Configure host/port via `application.Options.Server` (or `WAILS_SERVER_HOST`/`WAILS_SERVER_PORT`)
- Native-only features (system tray, native dialogs/menus, window manipulation) are no-ops in this headless mode, as expected

It's currently marked **experimental**, but it covers exactly this use case, so I'll close this. Please open a fresh issue if you hit gaps with it. Thanks!
