### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RonaldinhoL** [wailsapp/wails#3224]
### Description

we got some log from client side, it seems there are some bug in wails lib

we got a stack as follow:

```
Panicwrap Error:  panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1e10cbf]

goroutine 1 [running, locked to thread]:
github.com/wailsapp/go-webview2/pkg/edge.(*ICoreWebView2).GetSettings(0x0)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/corewebview2.go:200 +0x5f
github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).GetSettings(...)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/chromium.go:457
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).setupChromium(0xc000326b00)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.7.1/internal/frontend/desktop/windows/frontend.go:525 +0x665
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).Run(0xc000326b00, {0x28bc528?, 0xc0006d3590})
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.7.1/internal/frontend/desktop/windows/frontend.go:162 +0x185
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc0006c7860)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.7.1/internal/app/app_production.go:18 +0x38
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00006d2c0)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.7.1/pkg/application/application.go:73 +0xbb
github.com/wailsapp/wails/v2.Run(0xc000277760?)
	C:/Users/Ronaldinho/go/pkg/mod/github.com/wailsapp/wails/v2@v2.7.1/wails.go:14 +0xa5
main.main()
	F:/xxx/main.go:178 +0x1d10
```

### To Reproduce

we couldn;t Reproduce it atm

### Expected behaviour

app can;t start

### System Details

```shell
we don't know in client side
```

**Comment by Kgermando** [comment]
Check your main.go

**Comment by leaanthony** [comment]
Can't help with more info. If you have any more details, feel free to reopen.
