### ISSUE TITLE
vue-ts template run failed

### ISSUE THREAD

**Issue by lzytaro** [wailsapp/wails#3358]
### Description

Init project with command:
```
wails init -n wailstest -t vue-ts -ide vscode
```
```
E:\golang\src\gitee.com\lzygitee\wailstest> wails dev
Wails CLI v2.8.0

Executing: go mod tidy
  • Generating bindings: Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:     
    > frontend@0.0.0 build E:\golang\src\gitee.com\lzygitee\wailstest\frontend
    > vue-tsc --noEmit && vite build
    
    
    E:\golang\src\gitee.com\lzygitee\wailstest\frontend\node_modules\@vue\language-core\out\generators\template.js:237
                            tagOffsetsMap[tag] ??= [];
                                               ^^^
    
    SyntaxError: Unexpected token '??='
        at wrapSafe (internal/modules/cjs/loader.js:1029:16)
        at Module._compile (internal/modules/cjs/loader.js:1078:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
        at Module.load (internal/modules/cjs/loader.js:979:32)
        at Function.Module._load (internal/modules/cjs/loader.js:819:12)
        at Module.require (internal/modules/cjs/loader.js:1003:19)
        at require (internal/modules/cjs/helpers.js:107:18)
        at Object.<anonymous> (E:\golang\src\gitee.com\lzygitee\wailstest\frontend\node_modules\@vue\language-core\out\index.js:18:14)
        at Module._compile (internal/modules/cjs/loader.js:1114:14)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! frontend@0.0.0 build: `vue-tsc --noEmit && vite build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the frontend@0.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\林志远\AppData\Roaming\npm-cache\_logs\2024-03-30T11_27_25_475Z-debug.log


  ERROR   exit status 1
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### To Reproduce

wails init -n wailstest -t vue-ts -ide vscode
wails dev

### Expected behaviour

expect run success

### Screenshots

![image](https://github.com/wailsapp/wails/assets/62502682/f1fbf0f6-f5d7-45c5-9457-7e58a448641f)

### System Details

```shell
Enviroument:

# Wails
Version | v2.8.0

# System
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                                                   |
| Version      | 2009 (Build: 22621)                                                                              |
| ID           | 22H2                                                                                             |
| Go Version   | go1.21.5                                                                                         |
| Platform     | windows                                                                                          |
| Architecture | amd64                                                                                            |
| CPU          | Intel(R) N100                                                                                    |
| GPU 1        | OrayIddDriver Device (Shanghai Best Oray Information Technology Co., Ltd.) - Driver: 17.1.58.818 |
| GPU 2        | Intel(R) UHD Graphics (Intel Corporation) - Driver: 31.0.101.3417                                |
| Memory       | 16GB                                                                                             |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 122.0.2365.92 |
| Nodejs     | N/A          | Installed | 14.21.3       |
| npm        | N/A          | Installed | 6.14.18       |
| *upx       | N/A          | Installed | upx 4.2.2     |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details:
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
```


### Additional context

_No response_

**Comment by lzytaro** [comment]
oh, I known. node need to upgrade to 16+

**Comment by leaanthony** [comment]
Thanks for letting us know. Doctor should be reporting on that. We'll fix it
