### ISSUE TITLE
Wails Doctor on Redhat

### ISSUE THREAD

**Issue by jtfogarty** [wailsapp/wails#3522]
### Description

I'm seeing the below;
```
# Dependencies
┌─────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version |
| *docker    | Unknown      | Not Found |         |
| gcc        | Unknown      | Not Found | 8.5.0   |
| libgtk-3   | Unknown      | Not Found |         |
| libwebkit  | Unknown      | Not Found |         |
| npm        | Unknown      | Not Found | 10.8.0  |
| pkg-config | Unknown      | Not Found | 1.4.2   |
| *upx       | Unknown      | Not Found |         |
└──────────── * - Optional Dependency ────────────┘

# Diagnosis
 WARNING  Your system has missing dependencies!
Fatal:
Required dependencies missing: gcc libgtk-3 libwebkit npm pkg-config
Please read this article on how to resolve this: https://wails.io/guides/resolving-missing-packages```

All these packages `gcc libgtk-3 libwebkit npm pkg-config` are there when I attempt to install using yum

### To Reproduce

I just am installing and it will not resolve 

### Expected behaviour

Wails doctor should see these packages

### Screenshots

none

### Attempted Fixes

none

### System Details

```shell
# Wails
Version         | v2.8.1
Package Manager | dnf

# System
┌───────────────────────────────────────────────────────────────┐
| OS           | Red Hat Enterprise Linux                       |
| Version      | 8.10                                           |
| ID           | rhel                                           |
| Go Version   | go1.22.3                                       |
| Platform     | linux                                          |
| Architecture | amd64                                          |
| CPU          | Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz |
| Memory       | 8GB                                            |
└───────────────────────────────────────────────────────────────┘
```

**Comment by jtfogarty** [comment]
I ran some go code that returned the below;

go run main.go
Package: GCC, Version: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Package: libgtk-3, Version: 3.22.30
Package: libwebkit, Version: 2.42.5
Package: npm, Version: 10.8.0
Package: pkg-config, Version: 1.4.2

**Comment by jtfogarty** [comment]
I do get this error when I run wails dev

panic: failed to init GTK

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/internal/frontend/desktop/linux/frontend.go:145 +0x307
sync.(*Once).doSlow(0x16e70b8, 0xff01f8)
	/usr/local/go/src/sync/once.go:74 +0x168
sync.(*Once).Do(0x16e70b8, 0xff01f8)
	/usr/local/go/src/sync/once.go:65 +0x3e
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x10474f8, 0xc00008d890}, 0xc00018c160, 0xc000118a20, 0xc00009c000, {0x1043bc0, 0xc000080500})
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/internal/frontend/desktop/linux/frontend.go:136 +0x71
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend({0x10474f8, 0xc00008d890}, 0xc00018c160, 0xc000118a20, 0xc00009c000, {0x1043bc0, 0xc000080500})
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/internal/frontend/desktop/desktop_linux.go:16 +0x7b
github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc00018c160)
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/internal/app/app_dev.go:219 +0x18ef
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc000127280)
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/pkg/application/application.go:58 +0x72
github.com/wailsapp/wails/v2.Run(0xc00018c160)
	/home/d905985/go/pkg/mod/github.com/wailsapp/wails/v2@v2.8.1/wails.go:14 +0x2f
main.main()
	/home/d905985/anchor01/main.go:19 +0x359

**Comment by AndroidKitKat** [comment]
Did you ever find a fix for this?

**Comment by leaanthony** [comment]
v3's `wails3 doctor` handles RHEL and other RPM-based distros correctly. It reads `/etc/os-release` to detect the distro ID (rhel, fedora, centos, etc.) and routes to the `dnf` package manager implementation, which checks for `webkitgtk6.0-devel`, `gtk4-devel`, and other build dependencies via `dnf list` and `dnf info`. This was a v2 doctor limitation. Closing — thanks for the report!
