### ISSUE TITLE
SelectFile() crash on MacOS

### ISSUE THREAD

**Issue by vlourme** [wailsapp/wails#358]
**Description**

Calling runtime.Dialog.SelectFile() causes a crash of the backend

Crash log:
```
WARN[0005] [Bridge] SelectFile() unsupported in bridge mode 
panic: open : no such file or directory [recovered]
	panic: interface conversion: interface {} is *os.PathError, not string

goroutine 91 [running]:
github.com/wailsapp/wails/lib/binding.(*Manager).ProcessCall.func1(0xc000315ce0)
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/binding/manager.go:325 +0x10b
panic(0x4493160, 0xc0005d8840)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
nullify/zeplin/utils.(*Credentials).LoadCombolist(0xc00021c4b0)
	/Users/vico/Development/Wails/nullify/nullify/zeplin/utils/Combolist.go:46 +0x113
reflect.Value.call(0x4493060, 0xc00021c4b0, 0x213, 0x4505fbd, 0x4, 0x4ef4440, 0x0, 0x0, 0xc0001a8000, 0x36, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x4493060, 0xc00021c4b0, 0x213, 0x4ef4440, 0x0, 0x0, 0x1, 0x0, 0x407d982)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/wailsapp/wails/lib/binding.(*boundMethod).call(0xc00051c100, 0xc0005dc1d0, 0x2, 0x1f, 0xc0001082f8, 0x0, 0x0, 0x0)
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/binding/method.go:149 +0x4ff
github.com/wailsapp/wails/lib/binding.(*Manager).processMethodCall(0xc000124320, 0xc0005a7820, 0xc00005bc48, 0x19, 0xc00005bc80, 0x1)
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/binding/manager.go:283 +0xa4
github.com/wailsapp/wails/lib/binding.(*Manager).ProcessCall(0xc000124320, 0xc0005a7820, 0x0, 0x0, 0x0, 0x0)
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/binding/manager.go:333 +0x31b
github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1.1(0x4af9b20, 0xc000124320, 0xc0005a7820, 0xc000516060, 0xc00063c100)
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/manager.go:70 +0x59
created by github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1
	/Users/vico/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/ipc/manager.go:69 +0xba1
Error: exit status 2
```

**Expected behaviour**
Should open a dialog file correctly.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.14 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 4.2.1 |
| Npm           | 6.13.7 |
| Node          | v10.15.3 |

**Comment by leaanthony** [comment]
Selecting files is unsupported in bridge mode but we should handle this better. I'd be interested in the code you used to make this happen.

**Comment by vlourme** [comment]
> Selecting files is unsupported in bridge mode but we should handle this better. I'd be interested in the code you used to make this happen.

Thanks for answering. Could you explain what is Bridge Mode?

For the code, it’s a from JS, I call a structure in Go which as a method that call SelectFile. I need to get a path to the selected file to read it then.

**Comment by leaanthony** [comment]
Bridge mode is when you run using `wails serve` Do you have an example of how to make this crash?
