### ISSUE TITLE
Panic error in golang

### ISSUE THREAD

**Issue by Slixe** [wailsapp/wails#359]
I'm getting a panic error using Wails:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89d8d3]

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x217)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:354 +0xb3
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_a81d70c5eb4a__webviewDispatchGoCallback(0x217)
	_cgo_gotypes.go:307 +0x2b
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewEval(0xbc01ba0, 0xbd1ba00, 0x0)
	_cgo_gotypes.go:139 +0x4d
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Eval.func2(0xc0000d6000, 0xbd1ba00, 0xbd1ba00)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:330 +0x68
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Eval(0xc0000d6000, 0xc001316100, 0x524, 0x0, 0x0)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:330 +0x97
github.com/wailsapp/wails/lib/renderer.(*WebView).evalJS.func1()
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview.go:102 +0x44
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x219)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:354 +0xb8
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_a81d70c5eb4a__webviewDispatchGoCallback(0x219)
	_cgo_gotypes.go:307 +0x2b
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewEval(0xbc01ba0, 0xba8aa00, 0x0)
	_cgo_gotypes.go:139 +0x4d
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Eval.func2(0xc0000d6000, 0xba8aa00, 0xba8aa00)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:330 +0x68
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Eval(0xc0000d6000, 0xc000485b80, 0x524, 0x0, 0x0)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:330 +0x97
github.com/wailsapp/wails/lib/renderer.(*WebView).evalJS.func1()
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview.go:102 +0x44
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x217)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:354 +0xb8
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_a81d70c5eb4a__webviewDispatchGoCallback(0x217)
	_cgo_gotypes.go:307 +0x2b
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewLoop(0xbc01ba0, 0x1, 0x0)
	_cgo_gotypes.go:180 +0x4d
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop.func1(0xc0000d6000, 0xc000000001, 0x0)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:279 +0x66
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop(0xc0000d6000, 0x1, 0x1)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:279 +0x34
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Run(0xc0000d6000)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview/webview.go:283 +0x30
github.com/wailsapp/wails/lib/renderer.(*WebView).Run(0xc0000bc070, 0xc92de0, 0xc0000bc070)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/lib/renderer/webview.go:235 +0x1d5
github.com/wailsapp/wails.(*App).start(0xc0000ba100, 0x0, 0x0)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/app.go:140 +0x575
github.com/wailsapp/wails.(*App).Run(0xc0000ba100, 0x911600, 0xbf0058)
	/home/slixe/go/pkg/mod/github.com/wailsapp/wails@v1.0.2/app.go:83 +0xaf
main.main()
	/home/slixe/Projects/DERO/wails/dero-wallet/main.go:410 +0x5bb
```

**Comment by leaanthony** [comment]
Please open a new ticket using `walls issue` and supply more information like the code that's causing the error. Thanks.
