### ISSUE TITLE
Application Crash on Dragging Non-File Content with EnableFileDrop Enabled

### ISSUE THREAD

**Issue by hempflower** [wailsapp/wails#3680]
### Description

When EnableFileDrop is enabled, dragging any non-file content (e.g., text) into the Wails application causes the application to crash.

### To Reproduce

1. Create a Wails application and enable the EnableFileDrop option in the configuration.
2. Run the application.
3. Drag any non-file content (e.g., a text snippet or an image from a website) into the application window.
4. Observe that the application crashes immediately upon dropping the content.

### Expected behaviour

When non-file content (e.g., text, images) is dragged into the application window with EnableFileDrop enabled, the application should either ignore the drop or handle it gracefully without crashing.

### Screenshots

![image](https://github.com/user-attachments/assets/7e157c97-2f6e-4dd3-adda-017770e37353)

### System Details

```shell
# Wails
Version | v2.9.1

# System
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                                                                   |
| Version      | 2009 (Build: 22631)                                                                              |
| ID           | 23H2                                                                                             |
| Go Version   | go1.19.1                                                                                         |
| Platform     | windows                                                                                          |
| Architecture | amd64                                                                                            |
| CPU          | AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx                                                    |
| GPU 1        | OrayIddDriver Device (Shanghai Best Oray Information Technology Co., Ltd.) - Driver: 17.1.58.818 |
| GPU 2        | NVIDIA GeForce GTX 1650 (NVIDIA) - Driver: 31.0.15.5123                                          |
| GPU 3        | AMD Radeon(TM) RX Vega 10 Graphics (Advanced Micro Devices, Inc.) - Driver: 27.20.1032.2         |
| Memory       | 16GB                                                                                             |
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 127.0.2651.98 |
| Nodejs     | N/A          | Installed | 18.19.1       |
| npm        | N/A          | Installed | 10.2.4        |
| *upx       | N/A          | Installed | upx 4.0.2     |
| *nsis      | N/A          | Installed | v3.09         |
└─────────────── * - Optional Dependency ───────────────┘
```

### Additional context

Crash Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x13042fe]

goroutine 1 [running, locked to thread]:
github.com/wailsapp/go-webview2/pkg/edge.(*ICoreWebView2File).Release(0x0)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/ICoreWebView2File.go:25 +0x1e
panic({0x1522b60?, 0x23809c0?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x136
github.com/wailsapp/go-webview2/pkg/edge.(*ICoreWebView2File).GetPath(0x0)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/ICoreWebView2File.go:31 +0x103
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessageWithAdditionalObjects(0xc000240100, {0xc000306888, 0x11}, 0x79e00027cc00, 0x79e0002e0d80)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/desktop/windows/frontend.go:746 +0x60e
github.com/wailsapp/go-webview2/pkg/edge.(*Chromium).MessageReceived(0xc000238480, 0x79e00027cc00, 0x79e0002e0d80)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/chromium.go:342 +0x3ee
github.com/wailsapp/go-webview2/pkg/edge._ICoreWebView2WebMessageReceivedEventHandlerInvoke(0xc00020a738, 0x79e00027cc00, 0x79e0002e0d80)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/go-webview2@v1.0.10/pkg/edge/ICoreWebView2WebMessageReceivedEventHandler.go:28 +0x38
syscall.SyscallN(0x7fff7ac97ba0, {0xc00020d608?, 0x1, 0x0?})
        C:/Program Files/Go/src/runtime/syscall_windows.go:544 +0x11d
syscall.(*Proc).Call(0xc00008c500, {0xc00020d608, 0x1, 0x1})
        C:/Program Files/Go/src/syscall/dll_windows.go:166 +0x7e
syscall.(*LazyProc).Call(0xc0001223c0, {0xc00020d608, 0x1, 0x1})
        C:/Program Files/Go/src/syscall/dll_windows.go:286 +0x95
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc/w32.DispatchMessage(0x2726a61c5e0)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/desktop/windows/winc/w32/user32.go:364 +0x8f
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/winc.RunMainLoop()
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/desktop/windows/winc/app.go:84 +0x107
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).RunMainLoop(0xc000240100)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/frontend/desktop/windows/frontend.go:212 +0x14
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc00021a5a0)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/internal/app/app_dev.go:33 +0x72
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc00006daa0)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/pkg/application/application.go:73 +0x18f
github.com/wailsapp/wails/v2.Run(0xc00017e160)
        C:/Users/hempf/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.1/wails.go:14 +0x2f
main.main()
        D:/aisong-client/aisongs/main.go:20 +0x446
[0814/235146.855:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

**Comment by angYuHao** [comment]
you can add the following code on  github.com\wailsapp\wails\v2@v2.9.1\internal\frontend\desktop\windows\frontend.go line 742
`if  _file == nil { return }`
like this
![image](https://github.com/user-attachments/assets/4e93b735-2f3f-4722-8773-2df5a3dc1b2b)

**Comment by leaanthony** [comment]
Fixed in https://github.com/wailsapp/wails/pull/3597
