### ISSUE TITLE
v2-mac fails to run 

### ISSUE THREAD

**Issue by txbrown** [wailsapp/wails#601]
**Description**
After changing to new api using  `	wails.Run()` to run the app, it now fails to open the window. The logs are not clear and sort of "swallowed". When I build and run the app I can see the app panics with the output seen below in "Additional context".

**To Reproduce**

Happy to share/publish the branch I am working on as I merge new updates coming from the `v2-mac`.

**System Details**
macOS Big Sur - 11.1 Beta
go version go1.15.6 darwin/amd64

**Additional context**

```
./build/darwin/desktop/kitchensink
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x44 pc=0x7fff201fb40d]

runtime stack:
runtime.throw(0x4345074, 0x2a)
        /usr/local/opt/go/libexec/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/opt/go/libexec/src/runtime/signal_unix.go:726 +0x48c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4288640, 0xc000987d60, 0x0)
        /usr/local/opt/go/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc000987d30 sp=0xc000987cf8 pc=0x400937b
github.com/wailsapp/wails/v2/internal/ffenestri._Cfunc_Run(0xa81e290, 0xc000000000, 0x0)
        _cgo_gotypes.go:335 +0x45 fp=0xc000987d60 sp=0xc000987d30 pc=0x4165a65
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run.func6(0xa81e290)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/ffenestri/ffenestri.go:171 +0x65 fp=0xc000987d90 sp=0xc000987d60 pc=0x4168785
github.com/wailsapp/wails/v2/internal/ffenestri.(*Application).Run(0xc0001567c0, 0x441f620, 0xc0009c6000, 0xc00001a380, 0x364, 0xc0004ec001, 0xc0004ea5a0, 0x0)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/ffenestri/ffenestri.go:171 +0x2e9 fp=0xc000987e00 sp=0xc000987d90 pc=0x4166f29
github.com/wailsapp/wails/v2/internal/app.(*App).Run(0xc0004bb4a0, 0xc0004bb4a0, 0x0)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/app/desktop.go:210 +0x607 fp=0xc000987e98 sp=0xc000987e00 pc=0x41741c7
github.com/wailsapp/wails/v2.Run(0xc000152000, 0xc00011afc0, 0x2)
        /Users/ricardoabreu/Development/oss/wails/v2/wails.go:24 +0x5c fp=0xc000987ec8 sp=0xc000987e98 pc=0x417473c
main.main()
        /Users/ricardoabreu/Development/oss/wails/v2/test/kitchensink/main.go:23 +0x3ee fp=0xc000987f88 sp=0xc000987ec8 pc=0x4280d4e
runtime.main()
        /usr/local/opt/go/libexec/src/runtime/proc.go:204 +0x209 fp=0xc000987fe0 sp=0xc000987f88 pc=0x403d049
runtime.goexit()
        /usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000987fe8 sp=0xc000987fe0 pc=0x406f561

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/opt/go/libexec/src/runtime/sigqueue.go:144 +0x9d
os/signal.loop()
        /usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/opt/go/libexec/src/os/signal/signal.go:150 +0x45

goroutine 22 [select]:
github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start.func1(0xc00010e1e0)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/signal/signal.go:64 +0xc5
created by github.com/wailsapp/wails/v2/internal/signal.(*Manager).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/signal/signal.go:63 +0xc9

goroutine 23 [select]:
github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start.func1(0xc00002a180)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/servicebus/servicebus.go:83 +0x173
created by github.com/wailsapp/wails/v2/internal/servicebus.(*ServiceBus).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/servicebus/servicebus.go:77 +0xce

goroutine 24 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start.func1(0xc0004ea0a0)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/runtime.go:70 +0x1c6
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Runtime).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/runtime.go:67 +0x3f

goroutine 25 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start.func1(0xc0004ea190)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/log.go:68 +0x17c
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Log).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/log.go:64 +0x5c

goroutine 26 [select]:
github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start.func1(0xc0009c6000)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/messagedispatcher/messagedispatcher.go:118 +0x265
created by github.com/wailsapp/wails/v2/internal/messagedispatcher.(*Dispatcher).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/messagedispatcher/messagedispatcher.go:115 +0x9e

goroutine 27 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start.func1(0xc0004ea460)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/event.go:89 +0x17a
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Event).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/event.go:86 +0x9b

goroutine 28 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start.func1(0xc0004ea500)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/menu.go:72 +0x17a
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Menu).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/menu.go:69 +0x9b

goroutine 29 [select]:
github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start.func1(0xc0004ea5a0)
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/call.go:77 +0x185
created by github.com/wailsapp/wails/v2/internal/subsystem.(*Call).Start
        /Users/ricardoabreu/Development/oss/wails/v2/internal/subsystem/call.go:74 +0x5a
```

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
V2 is not ready yet so this is likely to happen.

**Comment by leaanthony** [comment]
@txbrown suggest we close this until beta out and we have more api stability?

**Comment by txbrown** [comment]
@leaanthony fair. Feel free to close it.

**Comment by leaanthony** [comment]
v2 Mac has been under intense development and the API is pretty much considered stable. Just letting you know 👍

**Comment by txbrown** [comment]
@leaanthony Will get back to it soon then. thanks so much! there is a cool project / purpose I already have for the new features. I have been quiet building, see you on slack.
