### ISSUE TITLE
i'm getting an error on Linux

### ISSUE THREAD

**Issue by owlreddy** [wailsapp/wails#679]
I just installed wails on POPOS and tried to create a project with CLI but I'm getting the below error. Can someone plz tell me how to fix it. Thank You. 

```The name of the project (My Project): y
Project Name: y
The output binary name (y):
Output binary Name: y
Project directory name (y):
Project Directory: y
Please select a template (* means unsupported on current platform):
  1: Angular - Angular 8 template (Requires node 10.8+)
  2: React JS - Create React App v4 template
  3: Svelte - A basic Svelte template
  4: Vanilla - A Vanilla HTML/JS template
  5: Vue3 Full - Vue 3, Vuex, Vue-router, and Webpack4
  6: Vue2/Webpack Basic - A basic Vue2/WebPack4 template
  7: Vuetify1.5/Webpack Basic - A basic Vuetify1.5/Webpack4 template
  8: Vuetify2/Webpack Basic - A basic Vuetify2/Webpack4 template
Please choose an option [1]: 5
Template: Vue3 Full
✓ Generating project...
⣽ Building project (this may take a while)...
Wails v1.16.3 - Building Application

⡿ Ensuring frontend dependencies are up to date (This may take a while)npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code 1
npm ERR! path /home/nani/work/wails/y/frontend/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /home/nani/work/wails/y/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/home/nani/work/wails/y/frontend/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.14.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/nani/work/wails/y/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/nani/work/wails/y/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/nani/work/wails/y/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/nani/work/wails/y/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/nani/work/wails/y/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/nani/work/wails/y/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/nani/work/wails/y/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/nani/work/wails/y/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/nani/work/wails/y/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/nani/work/wails/y/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/nani/work/wails/y/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/nani/work/wails/y/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/nani/work/wails/y/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/nani/work/wails/y/frontend/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/nani/work/wails/y/frontend/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/nani/work/wails/y/frontend/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/nani/work/wails/y/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/nani/work/wails/y/frontend/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/nani/work/wails/y/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/nani/work/wails/y/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:193:21)
npm ERR! gyp ERR! System Linux 5.11.0-7612-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/nani/work/wails/y/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/nani/work/wails/y/frontend/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nani/.npm/_logs/2021-04-15T19_50_44_445Z-debug.log


✗ Ensuring frontend dependencies are up to date (This may take a while)
Error: exit status 1

✗ exit status 1
Error: exit status 1```

**Comment by leaanthony** [comment]
Looks like your npm setup is amiss. Looks like a dependency needs python?

**Comment by csor-dev** [comment]
I'll need python2 for this?

**Comment by csor-dev** [comment]
@leaanthony  just installed python2 and it seems to be working fine. But I'm not sure why python2 is used here, can you tell me why python2 is being used for?

**Comment by leaanthony** [comment]
Glad it was sorted. Looks like it's a dependency of a vue3 dependency.
