### ISSUE TITLE
wails build fails with React v17

### ISSUE THREAD

**Issue by KoduIsGreat** [wailsapp/wails#726]
**Description**
Upgrading react version to 17 causes build errors due to webpack and wails-react-scripts not using the latest version of react-scripts (I think).

**To Reproduce**
Steps to reproduce the behaviour:
1. create a new project with wails init
2. upgrade react versions by running the following command `npm install react-scripts@4.0.0 react@17.0.0 react-dom@17.0.0`
3. run wails build
```
aashe@DESKTOP-MI1RQ6S MINGW64 /c/Repositories/WaterFALL/desktop (wails)
$ wails build
Wails v1.16.3 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
\ Building frontend...
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The wails-react-scripts package provided by Create React App requires a dependency:

  "babel-eslint": "10.0.1"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-eslint was detected higher up in the tree:

  C:\Repositories\WaterFALL\desktop\frontend\node_modules\babel-eslint (version: 10.1.0)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Repositories\WaterFALL\desktop\frontend\node_modules\babel-eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-eslint in your project folder.
     This will tell you which other package (apart from the expected wails-react-scripts) installed babel-eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! desktop@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the desktop@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aashe\AppData\Roaming\npm-cache\_logs\2021-05-27T17_19_10_863Z-debug.log


> desktop@0.1.0 build C:\Repositories\WaterFALL\desktop\frontend
> react-scripts build


! Building frontend...
Error: exit status 1
```
Also did the following to see what was conflicting:
```
aashe@DESKTOP-MI1RQ6S MINGW64 /c/Repositories/WaterFALL/desktop/frontend (wails)
$ npm ls babel-eslint
desktop@0.1.0 C:\Repositories\WaterFALL\desktop\frontend
+-- react-scripts@4.0.3
| `-- babel-eslint@10.1.0
`-- wails-react-scripts@3.0.1-2
  `-- babel-eslint@10.0.1

```
**Expected behaviour**
Either this is a bug or just a lacking documentation issue that wails doesn't support react v17. preferbly build should succeed but that seems to require an update to the js tooling used by wails.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.3 |
| Go Version    | go1.16 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 8.1.0 |
| Npm           | 6.14.6 |
| Node          | v12.18.4
 |

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by KoduIsGreat** [comment]
Note, i realized that i probably should have wails-react-scripts and react-scripts installed, I did the above also without installing react-scripts and received an error like the following:
```
aashe@DESKTOP-MI1RQ6S MINGW64 /c/Repositories/WaterFALL/desktop (wails)
$ wails build
Wails v1.16.3 - Building Application

> Ensuring frontend dependencies are up to date (This may take a while)
- Building frontend...internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'acorn'
Require stack:
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\acorn-dynamic-import\lib\index.js
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\wails-react-scripts\node_modules\webpack\lib\Parser.js
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\wails-react-scripts\node_modules\webpack\lib\JavascriptModulesPlugin.js
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\wails-react-scripts\node_modules\webpack\lib\WebpackOptionsApply.js
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\wails-react-scripts\node_modules\webpack\lib\webpack.js
- C:\Repositories\WaterFALL\desktop\frontend\node_modules\wails-react-scripts\scripts\build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Repositories\WaterFALL\desktop\frontend\node_modules\acorn-dynamic-import\lib\index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\acorn-dynamic-import\\lib\\index.js',
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\wails-react-scripts\\node_modules\\webpack\\lib\\Parser.js',
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\wails-react-scripts\\node_modules\\webpack\\lib\\JavascriptModulesPlugin.js',
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\wails-react-scripts\\node_modules\\webpack\\lib\\WebpackOptionsApply.js',
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\wails-react-scripts\\node_modules\\webpack\\lib\\webpack.js',
    'C:\\Repositories\\WaterFALL\\desktop\\frontend\\node_modules\\wails-react-scripts\\scripts\\build.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! desktop@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the desktop@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aashe\AppData\Roaming\npm-cache\_logs\2021-05-27T18_11_29_099Z-debug.log


> desktop@0.1.0 build C:\Repositories\WaterFALL\desktop\frontend
> react-scripts build


! Building frontend...
Error: exit status 1

```

**Comment by leaanthony** [comment]
Hi. We can only support the default templates but that doesn't mean react 17 won't work. The frontend project can be whatever you like, the only thing Wails cares about is that you define what the install and build commands are in `project.json`. If you want to use something else, then your best bet is to generate a hello world style app in frontend and ensure you update `project.json`. This would be far easier than to try and upgrade a template.

From your error message it looks like you need to install acorn.

**Comment by KoduIsGreat** [comment]
@leaanthony Thanks! i will give this a shot.

**Comment by leaanthony** [comment]
@KoduIsGreat can this be closed?
