### ISSUE TITLE
MacOS - Fresh install: unexpected return pc for runtime.sigpanic

### ISSUE THREAD

**Issue by guiguir68** [wailsapp/wails#780]
**Description**

Hi!
I cannot use "wails serve" or exec the compilled project on a fresh install of Go/Wails on MacOS BigSur 11.5.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Install go
2. Install npm
3. Install xcode
4. Install wails
5. Create a new Wails project:
  - wails setup
  - wails init
  - cd test-wails
  - wails build
  - wails serve

**Output of "wails serve" command**
```
Wails v1.16.6 - Serving Application

✓ Ensuring Dependencies are up to date...
✓ Packing + Compiling project...
Awesome! Project 'test-wails' built!
Serving Application: /Users/guillaume/Dev/test-wails/build/test-wails
test-wails - Debug Build
------------------------
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2047dc9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2047dc9e
stack: frame={sp:0x7ffeefbff1a8, fp:0x7ffeefbff1f8} stack=[0x7ffeefb80248,0x7ffeefbff2b0)
0x00007ffeefbff0a8:  0x01007ffeefbff0c8  0x0000000000000004
0x00007ffeefbff0b8:  0x000000000000001f  0x00007fff2047dc9e
0x00007ffeefbff0c8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff0d8:  0x0000000004035911 <runtime.throw+0x0000000000000071>  0x00007ffeefbff178
0x00007ffeefbff0e8:  0x00000000043bcce6  0x00007ffeefbff130
0x00007ffeefbff0f8:  0x0000000004035bc8 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000048041e0
0x00007ffeefbff108:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff118:  0x00007ffeefbff178  0x0000000004035911 <runtime.throw+0x0000000000000071>
0x00007ffeefbff128:  0x00000000048041e0  0x00007ffeefbff168
0x00007ffeefbff138:  0x0000000004035b50 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff148
0x00007ffeefbff148:  0x0000000004035b80 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000048041e0
0x00007ffeefbff158:  0x0000000004035911 <runtime.throw+0x0000000000000071>  0x00007ffeefbff178
0x00007ffeefbff168:  0x00007ffeefbff198  0x0000000004035911 <runtime.throw+0x0000000000000071>
0x00007ffeefbff178:  0x00007ffeefbff180  0x0000000004035940 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff188:  0x00000000043c2991  0x000000000000002a
0x00007ffeefbff198:  0x00007ffeefbff1e8  0x000000000404b2d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff1a8: <0x00000000043c2991  0x00000000048041e0
0x00007ffeefbff1b8:  0x00007ffeefbff228  0x0000000000000000
0x00007ffeefbff1c8:  0x00000000048047a0  0x0000000000000000
0x00007ffeefbff1d8:  0x000000c000167a30  0x000000000407a1c0 <syscall.libc_write_trampoline+0x0000000000000000>
0x00007ffeefbff1e8:  0x00007ffeefbff230 !0x00007fff2047dc9e
0x00007ffeefbff1f8: >0x00007ffeefbff230  0x000000000475c000
0x00007ffeefbff208:  0x0000000000000494  0x00000000042abca5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff218:  0x0000000004067c5f <runtime.syscall+0x000000000000001f>  0x000000c000167330
0x00007ffeefbff228:  0x00000000040675cc <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c000167300
0x00007ffeefbff238:  0x0000000004065ad0 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff270
0x00007ffeefbff248:  0x000000000400f9ee <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000020
0x00007ffeefbff258:  0x0000000000000010  0x00000000048382c0
0x00007ffeefbff268:  0x0000000000000d28  0x000000c0000001a0
0x00007ffeefbff278:  0x0000000004063be9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff288:  0x00000000044fc4c0  0x00000000048041e0
0x00007ffeefbff298:  0x00007ffeefbff2e0  0x0000000004063ae5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff2a8:  0x0000000004063a9d <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x43c2991, 0x48041e0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2047dc9e
stack: frame={sp:0x7ffeefbff1a8, fp:0x7ffeefbff1f8} stack=[0x7ffeefb80248,0x7ffeefbff2b0)
0x00007ffeefbff0a8:  0x01007ffeefbff0c8  0x0000000000000004
0x00007ffeefbff0b8:  0x000000000000001f  0x00007fff2047dc9e
0x00007ffeefbff0c8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff0d8:  0x0000000004035911 <runtime.throw+0x0000000000000071>  0x00007ffeefbff178
0x00007ffeefbff0e8:  0x00000000043bcce6  0x00007ffeefbff130
0x00007ffeefbff0f8:  0x0000000004035bc8 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000048041e0
0x00007ffeefbff108:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff118:  0x00007ffeefbff178  0x0000000004035911 <runtime.throw+0x0000000000000071>
0x00007ffeefbff128:  0x00000000048041e0  0x00007ffeefbff168
0x00007ffeefbff138:  0x0000000004035b50 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff148
0x00007ffeefbff148:  0x0000000004035b80 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000048041e0
0x00007ffeefbff158:  0x0000000004035911 <runtime.throw+0x0000000000000071>  0x00007ffeefbff178
0x00007ffeefbff168:  0x00007ffeefbff198  0x0000000004035911 <runtime.throw+0x0000000000000071>
0x00007ffeefbff178:  0x00007ffeefbff180  0x0000000004035940 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff188:  0x00000000043c2991  0x000000000000002a
0x00007ffeefbff198:  0x00007ffeefbff1e8  0x000000000404b2d6 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff1a8: <0x00000000043c2991  0x00000000048041e0
0x00007ffeefbff1b8:  0x00007ffeefbff228  0x0000000000000000
0x00007ffeefbff1c8:  0x00000000048047a0  0x0000000000000000
0x00007ffeefbff1d8:  0x000000c000167a30  0x000000000407a1c0 <syscall.libc_write_trampoline+0x0000000000000000>
0x00007ffeefbff1e8:  0x00007ffeefbff230 !0x00007fff2047dc9e
0x00007ffeefbff1f8: >0x00007ffeefbff230  0x000000000475c000
0x00007ffeefbff208:  0x0000000000000494  0x00000000042abca5 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff218:  0x0000000004067c5f <runtime.syscall+0x000000000000001f>  0x000000c000167330
0x00007ffeefbff228:  0x00000000040675cc <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c000167300
0x00007ffeefbff238:  0x0000000004065ad0 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff270
0x00007ffeefbff248:  0x000000000400f9ee <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000020
0x00007ffeefbff258:  0x0000000000000010  0x00000000048382c0
0x00007ffeefbff268:  0x0000000000000d28  0x000000c0000001a0
0x00007ffeefbff278:  0x0000000004063be9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff288:  0x00000000044fc4c0  0x00000000048041e0
0x00007ffeefbff298:  0x00007ffeefbff2e0  0x0000000004063ae5 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff2a8:  0x0000000004063a9d <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x42abca0, 0x1, 0x40487413, 0xc0001673c0)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000167330 sp=0xc000167310 pc=0x406271b
syscall.syscall(0x38, 0x8, 0x38, 0xc000167910)
	<autogenerated>:1 +0x26 fp=0xc000167378 sp=0xc000167330 pc=0x4068466
golang.org/x/sys/unix.ioctl(0x0, 0xc0001674b8, 0x10)
	/Users/guillaume/go/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc0001673a8 sp=0xc000167378 pc=0x42ab939
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/guillaume/go/pkg/mod/golang.org/x/sys@v0.0.0-20200323222414-85ca7c5b95cd/unix/ioctl.go:63
github.com/sirupsen/logrus.isTerminal(0x400f274)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/terminal_check_bsd.go:10 +0x50 fp=0xc000167418 sp=0xc0001673a8 pc=0x42b1a50
github.com/sirupsen/logrus.checkIfTerminal({0x4500e60, 0xc000010018})
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/terminal_check_notappengine.go:13 +0x75 fp=0xc000167430 sp=0xc000167418 pc=0x42b1af5
github.com/sirupsen/logrus.(*TextFormatter).init(...)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/text_formatter.go:86
github.com/sirupsen/logrus.(*TextFormatter).Format.func1()
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/text_formatter.go:174 +0x3b fp=0xc000167460 sp=0xc000167430 pc=0x42b319b
sync.(*Once).doSlow(0x4507b28, 0xc00000e2e8)
	/usr/local/go/src/sync/once.go:68 +0xd2 fp=0xc0001674c8 sp=0xc000167460 pc=0x406e532
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00007a2d0, 0xc000222850)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/text_formatter.go:174 +0xebe fp=0xc000167a38 sp=0xc0001674c8 pc=0x42b2b3e
github.com/sirupsen/logrus.(*Entry).write(0xc000222850)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/entry.go:255 +0xa5 fp=0xc000167ab0 sp=0xc000167a38 pc=0x42ad285
github.com/sirupsen/logrus.Entry.log({0xc0001769a0, 0xc00022e120, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/entry.go:231 +0x22e fp=0xc000167b30 sp=0xc000167ab0 pc=0x42acf2e
github.com/sirupsen/logrus.(*Entry).Log(0xc0002227e0, 0x4, {0xc000167d28, 0x10, 0x4334a40})
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/entry.go:268 +0xa8 fp=0xc000167c38 sp=0xc000167b30 pc=0x42ad488
github.com/sirupsen/logrus.(*Logger).Log(0xc0001769a0, 0x4, {0xc000167d28, 0x1, 0x1})
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/logger.go:192 +0x65 fp=0xc000167c78 sp=0xc000167c38 pc=0x42b0225
github.com/sirupsen/logrus.(*Logger).Info(...)
	/Users/guillaume/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/logger.go:206
github.com/wailsapp/wails/lib/logger.(*CustomLogger).Info(...)
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/lib/logger/custom.go:18
github.com/wailsapp/wails.(*App).start(0xc00015a780)
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/app.go:106 +0xdd fp=0xc000167da0 sp=0xc000167c78 pc=0x4308b1d
github.com/wailsapp/wails.(*App).start-fm()
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/app.go:100 +0x26 fp=0xc000167db8 sp=0xc000167da0 pc=0x4309ae6
github.com/wailsapp/wails/cmd.(*Command).Run(0xc000078a80, {0xc0000201e0, 0xc000202780, 0xc000021af0})
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/cmd/cli.go:170 +0xfb fp=0xc000167e28 sp=0xc000167db8 pc=0x42e82fb
github.com/wailsapp/wails/cmd.(*Cli).Run(0xc00006ca60, {0x0, 0x0, 0x0})
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/cmd/cli.go:47 +0xa5 fp=0xc000167e58 sp=0xc000167e28 pc=0x42e7d05
github.com/wailsapp/wails.(*App).Run(0xc000202780)
	/Users/guillaume/go/pkg/mod/github.com/wailsapp/wails@v1.16.6/app.go:89 +0x45 fp=0xc000167eb8 sp=0xc000167e58 pc=0x4308945
main.main()
	/Users/guillaume/Dev/test-wails/main.go:29 +0x10d fp=0xc000167f80 sp=0xc000167eb8 pc=0x4309f4d
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc000167fe0 sp=0xc000167f80 pc=0x4037fa7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000167fe8 sp=0xc000167fe0 pc=0x4065dc1
Error: exit status 2
```

I've the same error if i run `./build/test-wails`.

And the same error by cloning the [CPU Usage App](https://github.com/plutov/packagemain/tree/master/16-wails-desktop-app) project (recommended in the wails' documentation > tutorials)

Notes: 
- I didn't change or add any code in this project.
- If i use `go run main.go`, the backend starts correctly.

**Expected behaviour**
Starting the backend of this new wails project.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.6 |
| Go Version    | go1.17 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | on |
| GCC           | 12.0.5 |
| Npm           | 7.20.6 |
| Node          | v16.6.1 |

Do you have any suggestions?
Thank's!

**Comment by songc316** [comment]
go version go1.16.7 is work.

**Comment by leaanthony** [comment]
Hey thanks for this. I wonder if the new register based changes have affected CGO... Will look into this 👍

**Comment by leaanthony** [comment]
I haven't. Happy to accept a PR for it though.

**Comment by ttnghia195** [comment]
I try with go 1.16 and it work

**Comment by bashbunni** [comment]
Actually this is related to the comment I left on the Gophers slack channel. I'm having the same issue here, but the issue is caused by me trying to connect to a remote database. The program runs fine and there's no issue connecting when I run `wails serve` or do `go run .` with the Wails portion commented out on my main.go file. I typically encounter this error when I do `go run .` with the Wails portion of my code included in main.go or when I try to run the built application.

**Comment by leaanthony** [comment]
Thanks for the feedback @bashbunni 
Just to clarify, yourissue is related to Logrus in v1 too or is it slightly different? I'm suggesting people on mac and windows move to v2 of the project at this point as it solves a lot of issues.

**Comment by bashbunni** [comment]
No it's different. I guess I could probably write an issue on it. I just am having the same seg violation error when I try to build and run the application. Let me try upgrading to v2 and see if that fixes it! If not, I'll create an issue.

**Comment by leaanthony** [comment]
Please include the output of `wails doctor` if you open an issue. Many thanks!

**Comment by leaanthony** [comment]
Assuming v2 fixed this. If not, please reopen 👍
