### ISSUE TITLE
Wails build command does not complete in Debian 11 (Bullseye)

### ISSUE THREAD

**Issue by tataDan** [wailsapp/wails#931]
**Description**

The wails build command ran for over one hour and did not complete nor show an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `wails init`
2. Change the install value in the project.json from `npm install` to `npm install --force` in order to resolve the `npm ERR! ERESOLVE unable to resolve dependency tree` as mentioned in #919.
3. Run `wails build`
4. See error below:
```
daniel@dellOptiplex9020:~/goPrograms/wails/my-project$ wails build
Wails v1.16.8 - Building Application

✓ Ensuring frontend dependencies are up to date (This may take a while)
⣻ Building frontend...

```
**Expected behaviour**
It was expected that the wails build command would either complete in a reasonable amount of time or report an error.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.16.8 |
| Go Version    | go1.17.1 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 10.2.1 |
| Npm           | 8.1.0 |
| Node          | v17.0.1 |

**Additional context**
Should the wails build command work even though Debian 11 is not listed as being officially supported?

**Comment by leaanthony** [comment]
Limiting which Linux distros are "allowed" is super hard. The best thing to do is run the `frontend:build` script (`npm run build`?) in the frontend dir and see what it says.

**Comment by tataDan** [comment]
This is the output from running `npm run build ?`:
```
daniel@dellOptiplex9020:~/goPrograms/wails/my-project/frontend$ npm run build ?

> my-app@0.0.0 build
> npx ng build --single-bundle true --output-hashing none --prod --bundle-styles false "?"

Project '?' does not support the 'build' target.
Error: Project '?' does not support the 'build' target.
    at BuildCommand.initialize (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/@angular/cli/models/architect-command.js:58:19)
    at async BuildCommand.validateAndRun (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/@angular/cli/models/command.js:127:9)
    at async Object.runCommand (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/@angular/cli/models/command-runner.js:178:24)
    at async default_1 (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/@angular/cli/lib/cli/index.js:32:31)
daniel@dellOptiplex9020:~/goPrograms/wails/my-project/frontend$ 
```

**Comment by leaanthony** [comment]
Looks like you have a questionmark in your config. Edit `project.json` and update.

**Comment by tataDan** [comment]
I could not find any questionmark in my project.json file.  Here it is:
```
{
 "name": "My Project",
 "description": "Enter your project description",
 "author": {
  "name": "Daniel",
  "email": "danielcasey@q.com"
 },
 "version": "0.1.0",
 "binaryname": "my-project",
 "frontend": {
  "dir": "frontend",
  "install": "npm install --force",
  "build": "npx ng build --single-bundle true --output-hashing none --prod --bundle-styles false",
  "bridge": "src",
  "serve": "npm run serve"
 },
 "tags": "",
 "WailsVersion": "",
 "CrossCompile": false,
 "Platform": "",
 "Architecture": "",
 "LdFlags": "",
 "GoPath": "",
 "UseFirebug": false
}
```
Perhaps I should have run `npm run build` (without the ? at the end).  Here is the output when I run that command:

```
daniel@dellOptiplex9020:~/goPrograms/wails/my-project/frontend$ npm run build

> my-app@0.0.0 build
> npx ng build --single-bundle true --output-hashing none --prod --bundle-styles false

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
 10% building 2/3 modules 1 active ...ails/my-project/frontend/src/styles.cssError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:449:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:481:5
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/webpack/lib/NormalModule.js:342:12
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/daniel/goPrograms/wails/my-project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)

```

**Comment by leaanthony** [comment]
This is an environment issue. Nothing to do with Wails.

**Comment by tataDan** [comment]
I uninstalled the nodejs package from nodejs.org and installed the npm package from the Debian 11 repository, and now the `wails build` works as expected. (This means that nodejs and npm are not as recent, but at least the wails build command is working.)

**Comment by leaanthony** [comment]
Glad it's fixed for you👍
